repository:
  name: SquareCheck-android
  description: repository
  has_issues: true
  has_wiki: false
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false

branches:
  - name: master
  protection:
    required_pull_request_reviews:
      required_approving_review_count: 2
      dismiss_stale_reviews: true
    required_status_checks:
      contexts: ["build"]
    restrictions: null
    required_linear_history: true
    enforce_admins: null